internal enum OverlayCommand
{
    ToggleRevealMap,
    ToggleInfiniteMoney,
    ToggleOneHitKill,
    ToggleHighDefense,
    ToggleCratePicker,
    EnableSelectedCratePickers,
    DisableSelectedCratePickers,
    ToggleCrateRouteLines,
    ToggleMaximumPower,
    ToggleFullTech,
    ToggleUnlimitedProduction,
    ToggleChronoLegionnaireNoCooldown,
    ToggleEliteUnits,
    ToggleFormationMode,
    ArrangeSelectedFormation,
    ToggleInfiniteRangeMode,
    ToggleSelectedInfiniteRange,
    ToggleInfiniteSpeedMode,
    ToggleSelectedInfiniteSpeed,
    ToggleSpinningMcvMode,
    ToggleSelectedSpinningMcvs,
    ToggleInstantBuild,
    ToggleBuildAnywhere,
    ToggleAutoRepair,
    ToggleSuperWeaponNoCooldown,
    AutoBuildFlakCannon,
    AutoBuildPatriotMissile,
    AutoBuildPrismTower,
    AutoBuildTeslaCoil,
    DeleteSelectedObjects,
    TakeOwnershipSelectedObjects,
    ToggleFastTurn,
    ToggleDisableGapGenerators,
    ToggleInvadeMode,
    ToggleGamePause,
    ExitProgram
}

internal readonly record struct OverlayState(
    bool RevealMap,
    bool InfiniteMoney,
    bool OneHitKill,
    bool HighDefense,
    bool EliteUnits,
    bool FormationMode,
    bool InfiniteRangeMode,
    bool InfiniteSpeedMode,
    bool SpinningMcvMode,
    bool CratePicker,
    bool CrateRouteLines,
    bool MaximumPower,
    bool FullTech,
    bool UnlimitedProduction,
    bool ChronoLegionnaireNoCooldown,
    bool InstantBuild,
    bool BuildAnywhere,
    bool AutoRepair,
    bool SuperWeaponNoCooldown,
    bool FastTurn,
    bool DisableGapGenerators,
    bool InvadeMode,
    bool GamePaused,
    bool RestrictedFeaturesAvailable);
